### ISSUE TITLE
Accept bigger numbers

### ISSUE THREAD

**Issue by ineiti** [Base32H/base32h.github.io#1]
It should use the `encodeBin` and `decodeBin` methods from the library, else it's not possible to encode / decode larger strings, e.g., `9cc36071ccb902a1de7e0d21a2c176d73894b1cf88ae4cc2ba4c95cd76f474f3`.

**Comment by YellowApple** [comment]
Howdy!  Just pushed up support for binary encoding/decoding in the homepage demo.  Includes support for hex, base64, and raw strings (not Unicode aware... yet).

**Comment by ineiti** [comment]
Still doesn't work, the issue should be re-opened:

![Screenshot 2020-10-26 at 12 46 34](https://user-images.githubusercontent.com/1545067/97168787-53dec980-1789-11eb-801c-8fd19e4bfd82.png)

**Comment by ineiti** [comment]
from what I remember, `encodeBin` and `decodeBin` could work with bigger numbers.

**Comment by YellowApple** [comment]
You need to select one of the binary options in that drop-down to use `encodeBin` / `decodeBin`:

<img width="714" alt="image" src="https://user-images.githubusercontent.com/2379422/97169104-b793d300-1746-11eb-8a26-0e004366a3ce.png">

It'll still complain about that binary data not aligning with a 5-byte boundary, but it'll at least encode (and re-decode with some added nulls at the front per that warning).

**Comment by ineiti** [comment]
Thanks, that works... Three questions:
- the answer is wrong now - if I `decode` the `encoded` result, I don't get the original value anymore. Base32 solves this problem with a special end-caracters.
- why have `hexadecimal` with a limitation and `binary (base 16)` without limitation? That took me by surprise...
- what is `binary (string)`?

Just think that most people will not care about opening an issue, so if they stumble on this, they'll just move on to the next tab in their browser...

**Comment by YellowApple** [comment]
> the answer is wrong now - if I `decode` the `encoded` result, I don't get the original value anymore. Base32 solves this problem with a special end-caracters.

It's the same value, but with leading zeroes.  The [spec](https://base32h.github.io/specification#binary) goes into further detail, but long story short, Base32H's binary encoding/decoding specification (i.e. what `encodeBin` and `decodeBin` implement) align the input data to a 5-byte boundary (since the binary spec operates on 5-byte / 8-Base32H-digit chunks).

> why have `hexadecimal` with a limitation and `binary (base 16)` without limitation? That took me by surprise...

The non-binary hexadecimal option is for numeric decoding (i.e. following the numeric spec).  Numeric decoding for the Javascript implementation does not (yet) support `BigInt`; until it does, its numeric encode/decode functions are inaccurate for anything larger than `Number.MAX_SAFE_INTEGER` (contrast with the Ruby implementation, which doesn't have this limitation).

> what is `binary (string)`?

It encodes whatever string you type-in as-is as binary data.
